apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-operator
subjects:
- kind: ServiceAccount
  name: argocd-operator
  namespace: {{ .Namespace }}
roleRef:
  kind: ClusterRole
  name: argocd-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-server
subjects:
- kind: ServiceAccount
  name: argocd-server
  namespace: {{ .Namespace }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
