apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-operator
  namespace: {{ .Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: argocd-server
  namespace: {{ .Namespace }}
