apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-operator
  namespace: {{ .Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: argocd-server
  namespace: {{ .Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-redis-ha
  namespace: {{ .Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
  namespace: {{ .Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-dex-server
  namespace: {{ .Namespace }}
